version: '3'

services:
  felscanner:
    image: rohanpandula/felscanner:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: felscanner
    ports:
      - "8082:5000"
    volumes:
      - felscanner_data:/data
      - iptscanner_data:/data/iptscanner/data
      - iptscanner_profile:/data/iptscanner/profile
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/New_York}
      - DATA_DIR=/data
      - PLEX_URL=${PLEX_URL:-}
      - PLEX_TOKEN=${PLEX_TOKEN:-}
      - LIBRARY_NAME=${LIBRARY_NAME:-Movies}
      - TELEGRAM_ENABLED=${TELEGRAM_ENABLED:-false}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
      - IPT_UID=${IPT_UID:-}
      - IPT_PASS=${IPT_PASS:-}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    # Alternative network configuration for Plex connection issues
    # Uncomment the line below and comment out the ports section
    # network_mode: host

volumes:
  felscanner_data:
    driver: local
  iptscanner_data:
    driver: local
  iptscanner_profile:
    driver: local

# Only needed if not using host network
networks:
  default:
    driver: bridge 
